version: "3"
services:
  nginx: 
    image: nginx:stable-alpine
    ports:
      - "80:80"
  node-app:
    deploy:
      replicas: 4
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    build: 
      context: . # location of dockerfile
      args: 
        NODE_ENV: production # so that dockerfile knonws that it is in production mode
    environment:
      - NODE_ENV=production # this is for this docker-compose file itself
      - MONGO_USER=${MONGO_USER} # grap this value from the ubuntu machine or deployment machine
      - MONGO_PASSWORD=${MONGO_PASSWORD} # grap this value from the ubuntu machine or deployment machine
      - SECRET_REDIS=${SECRET_REDIS}
    command: node index.js
  database:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}