version: "3"
services:
  nginx: 
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro # readonly
  node-app:
    build: neiiila/node-app  # instead of "." which creates container based on docker file existed in current directory, it will be based on my pushed image pushed in docker hub 
    # ports: 
    #   - "3000:5000" # No need to expose the port where ngnix is proxy 
    environment:
      - PORT=5000
      - NAME=NADIA
    depends_on:
      - database # means that this container will not start until the database container is up and running
      # eventhough I start just the node-app service, the database service will start first also cuz of the depends_on (command : docker-compose -f .\docker-compose.yml -f .\docker-compose.dev.yml up -d node-app) 
      # you can avoid it by --no-deps flag (command : docker-compose -f .\docker-compose.yml -f .\docker-compose.dev.yml up -d --no-deps node-app)
  database: 
    image: mongo:4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - mongo-db:/data/db
  sessionDb:
    image: redis

volumes:
  mongo-db: