version: "3"
services:
  nginx: 
    image: nginx:stable-alpine
    ports:
      - "80:80"
  node-app:
    build: 
      context: . # location of dockerfile
      args: 
        NODE_ENV: production # so that dockerfile knonws that it is in production mode
    environment:
      - NODE_ENV=production # this is for this docker-compose file itself
      - MONGO_USER=${MONGO_USER} # grap this value from the ubuntu machine or deployment machine
      - MONGO_PASSWORD=${MONGO_PASSWORD} # grap this value from the ubuntu machine or deployment machine
      - SECRET_REDIS=${REDIS_SECRET}
    command: node index.js
  mongo:
    image: mongo:4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}