version: "3" # docker compose verision 
services : # each container is like a service
  node-app: # service name
    # configuratio of this container 
    build: . # build the container from the current directory cuz dockerfile exist in this directory 
    ports: # - for a list 
      - "3000:5000" # host:container
    volumes: # - for a list of volumes
      - .:/myWorkingDirectory # host:container
      - /myWorkingDirectory/node_modules # container only
    environment: # list of variable environment 
      - PORT=5000
      - NAME=NADIA
    #OR
    #env-file:
    # - ./.env